apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: trove-rabbitmq-test
  namespace: cluster-rabbitmq
spec:
  replicas: 3
  image: docker.io/rabbitmq:4.1-management

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  persistence:
    storageClassName: standard
    storage: 10Gi

  rabbitmq:
    additionalConfig: |
      default_queue_type = quorum
      channel_max = 2047
      heartbeat = 60
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      cluster_formation.node_cleanup.interval = 30
      cluster_formation.node_cleanup.only_log_warning = true
      cluster_formation.target_cluster_size_hint = 3

  override:
    service:
      spec:
        type: NodePort
        ports:
          - name: amqp
            port: 5672
            targetPort: 5672
            nodePort: 30673
    statefulSet:
      spec:
        template:
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: app.kubernetes.io/name
                            operator: In
                            values:
                              - trove-rabbitmq
                      topologyKey: kubernetes.io/hostname